# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sy', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='M_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_adult', models.CharField(max_length=20)),
                ('price_discount', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('rest', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
                ('hy', models.CharField(max_length=600)),
                ('intro', models.CharField(max_length=1000)),
                ('img1', models.ImageField(blank=True, upload_to='media/')),
                ('img2', models.ImageField(blank=True, upload_to='media/')),
                ('img3', models.ImageField(blank=True, upload_to='media/')),
                ('img4', models.ImageField(blank=True, upload_to='media/')),
                ('img5', models.ImageField(blank=True, upload_to='media/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team2.Area')),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team2.M_Type')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team2.Museum'),
        ),
    ]
